---
title: "Performing Lasso and Ridge on Data"
author: "Garrett Marshall"
date: "`r Sys.Date()`"
output: word_document
---


```{r message=FALSE}
library(NFLPlayPredictionProject)
library(tidyverse)
library(lubridate)
library(caTools)
library(caret)
library(randomForest)
library(ranger)
library(glmnet)
```

```{r}
data_1 <- games_pbp
```

```{r}
data_1$time_period <- ms(data_1$time)

data_1$time_seconds <- as.numeric(data_1$time_period, "seconds")

data_1$adjusted_time_seconds <- ifelse(data_1$quarter == 1, data_1$time_seconds + 45 * 60,
                                     ifelse(data_1$quarter == 2, data_1$time_seconds + 30 * 60,
                                            ifelse(data_1$quarter == 3, data_1$time_seconds + 15 * 60, data_1$time_seconds)))

data_1$adjusted_time_period <- seconds_to_period(data_1$adjusted_time_seconds)

data_1$adjusted_time <- format(data_1$adjusted_time_period, "%M:%S")

d_1 <- data_1 %>%
  mutate( time = adjusted_time_period ) %>%
  select( -c('time_period', 'time_seconds', 'adjusted_time_seconds', 'adjusted_time_period', 'adjusted_time') )

d_1 <- d_1 %>% select( -c('game', 'possession_team', 'possession_abbr') )

d_1$yards_to_first <- as.numeric(d_1$yards_to_first)
d_1$yards_to_endzone <- as.numeric(d_1$yards_to_endzone)
d_1$quarter <- as.numeric(d_1$quarter)
d_1$shotgun <- as.numeric(d_1$shotgun)
d_1$down <- as.numeric(d_1$down)
```

```{r}
# pass == 1
# run == 2
d_1$run_pass <- as.numeric(d_1$run_pass)
```



```{r}
# Split the dataset into training and test sets
set.seed(1234)
split <- sample.split(d_1$run_pass, SplitRatio = 0.8)
train <- subset(d_1, split == TRUE)
test <- subset(d_1, split == FALSE)
```

```{r}
# Predictor variables
x <- model.matrix( run_pass ~ ., train )[,-1]
# Outcome variable
y <- train$run_pass
```


```{r}
# RIDGE
# Find the best lambda using cross-validation
set.seed(123) 
cv <- cv.glmnet(x, y, alpha = 0)
# Display the best lambda value
cv$lambda.min
```

```{r}
# Fit the final model on the training data
ridge_model <- glmnet(x, y, alpha = 0, lambda = cv$lambda.min)
# Display regression coefficients
coef(ridge_model)
```

```{r}
# Make predictions on the test data
x.test <- model.matrix( run_pass ~ ., test )[,-1]
predictions <- ridge_model %>% predict(x.test) %>% as.vector()
# Model performance metrics
data.frame(
  RMSE = RMSE(predictions, test$run_pass),
  Rsquare = R2(predictions, test$run_pass)
)
```


```{r}
# LASSO
# Find the best lambda using cross-validation
set.seed(123) 
cv <- cv.glmnet(x, y, alpha = 1)
# Display the best lambda value
cv$lambda.min
```

```{r}
# Fit the final model on the training data
lasso_model <- glmnet(x, y, alpha = 1, lambda = cv$lambda.min)
# Display regression coefficients
coef(lasso_model)
```

```{r}
# Make predictions on the test data
x.test <- model.matrix( run_pass ~ ., test )[,-1]
predictions <- lasso_model %>% predict(x.test) %>% as.vector()
# Model performance metrics
data.frame(
  RMSE = RMSE(predictions, test$run_pass),
  Rsquare = R2(predictions, test$run_pass)
)
```


```{r}
# Build the model using the training set
set.seed(123)
enet_model <- train(
  run_pass ~ ., data = train, method = "glmnet",
  trControl = trainControl("cv", number = 10),
  tuneLength = 10
)
# Best tuning parameter
enet_model$bestTune

```

```{r}
coef(enet_model$finalModel, enet_model$bestTune$lambda)
```

```{r}
# Make predictions on the test data
x.test <- model.matrix( run_pass ~ ., test )[,-1]
predictions <- enet_model %>% predict(x.test)
# Model performance metrics
data.frame(
  RMSE = RMSE(predictions, test$run_pass),
  Rsquare = R2(predictions, test$run_pass)
)


```


